### PR TITLE
Implemented UserDAO, WeightGoalDAO.

### PR DESCRIPTION
**Pull request by AaryaB04**
Also added attributes to the user entity and initial commits for weight goal use case files.

### CODE REVIEW

**Review by anastasiajiv — APPROVED** [review]
The code looks good, however restrictions should be split into three sections: allergies, conditions, and dietary (this would be for the commonUserFactory, CommonUser and UserFactory), so they should be their own attributes. Also, perhaps for the WeightGoalInputData the restrictictions attribute should be removed.

**Comment by sophiali54** [comment]
I agree with Anastasia, restrictions should be split into the three categories with their own attributes and reflected in the factories.

**Comment by sophiali54** [comment]
It seems to be that it's still flagging conflicts despite your reversion and fixes, should we create a new pull request perhaps?

**Comment by sophiali54** [comment]
Entered branch and resolved merge conflicts; awaiting second approval.

**Review by eshaa04 — APPROVED** [review]

**Pull request merged**
